### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by tanya1810** [tanya1810/sudoku-solver#2]
Add a detailed readme file for my sudoku solver web app

**Comment by UshasriMavuri1999** [comment]
Can you please assign this issue to me?

**Comment by codewithvk** [comment]
Can you please assign this issue to me?

**Comment by roshnaeem** [comment]
hey @tanya1810, can I work on this issue? I have made a readme file for a similar project of mine too and it seems exciting.

**Comment by ridsuteri** [comment]
hey @tanya1810 , plz assign this issue to me, i am a begineer and want to contribute !

**Comment by jay-deep** [comment]
This is my first time in open source contribution, Can i get this?
